"""create users model

Revision ID: 7eb244fc648b
Revises: 
Create Date: 2023-11-12 10:31:57.263357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7eb244fc648b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("DROP TYPE IF EXISTS user_role_enum;")
    op.execute(
        "CREATE TYPE user_role_enum as ENUM('client', 'manager', 'admin', 'credit_officer');"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('username', sa.String(length=255), nullable=False),
                    sa.Column('first_name', sa.String(length=255), nullable=False),
                    sa.Column('last_name', sa.String(length=255), nullable=False),
                    sa.Column('phone_number', sa.String(length=13), nullable=True),
                    sa.Column('email', sa.String(length=200), nullable=True),
                    sa.Column('role',
                              postgresql.ENUM('client', 'manager', 'admin', 'credit_officer', name='user_role_enum',
                                              create_type=False), nullable=True),
                    sa.Column('hashed_password', sa.String(length=300), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.execute("DROP TYPE IF EXISTS user_role_enum;")
    # ### end Alembic commands ###
